language: node_js

node_js:
  - "8"
  - "6"
  - "4"

env:
  - TEST_COV=true
  - TEST_COV=false

matrix:
  exclude:
    - node_js: "4"
      env: TEST_COV=true
    - node_js: "6"
      env: TEST_COV=true
    - node_js: "8"
      env: TEST_COV=false

script:
  - 'make test-es5'
  - '[ "$TEST_COV" = "false" ] || make test-coveralls'
